### PR TITLE
Integrate extension `debug`

### PR DESCRIPTION
**Pull request by SimonSimCity**
I've just added a bit of debugging to track down an error I have with this extension and I thought it would be a good addition to add these debug printings of mine to the main library in case someone else also wants to debug this.

### CODE REVIEW

**Comment by nlhuykhang** [comment]
Hey, thanks for the PR. I think it is a very good idea, here are my comments:

1. It is not a good idea to strictly depend on `debug` as the only logging method on the module level, because:
    - introduce new dependency, this should be avoided if possible
    - users cannot choose the their own logging method
    - most users may not care about debugging the module at all, but this still includes `debug` in their project
2. I think there are too many debug messages. It is surely helpful for us who works on the module, but from users' POV they have no ideas what those messages mean. What matters most for them are:
    - when the job starts/stops
    - when the value is published (really sent out to client)

For my first comment, I think it makes more sense to make logging as an extension per context level, for example:

```
const log = debug('numComments');

JoinServer.publish({
  context: this,
  name: 'numComments',
  interval: /*...*/,
  logging(message) {
    /*
        user choose their preferable logging method here
        this option is also optional, no logging if nothing is specifided
    */
    
    console.log(message);
    // or
    console.error(message);
    // or
    log(message);
    // or remote log
    http.post("remote_log_url", message);
  },
  doJoin() { /*...*/ },
});
```

Lastly, What do you think about becoming a collaborator of this module? cause I do not actively work with Meteor these days, it is better to have someone like you to share the work to ensure the module keeps on living with high quality. It is open source anyway, collaboration is a must 🙂.

**Comment by SimonSimCity** [comment]
I've now changed the implementation to support the following:

* Dependency on `debug` is removed
* Implemented a `log` method on both every `publish()` method and on the server (server is used if the `publish()` method doesn't provide a custom logger)
* Introduced log levels, compatible with those `winston` uses (which in turn is compatible with [RFC5424](https://tools.ietf.org/html/rfc5424#page-11))
* Replaced a `console.error()` I found to use this log method, which by default calls `console.error()` to keep the old behavior

To your last question: It would be nice if you could add me both here in this repository and on NPM as a collaborator of the project. I'll still promise to keep in contact with you to confirm that the extension runs in a good way.

**Comment by nlhuykhang** [comment]
Great, I add your as collaborator now. Please help update the readme for log function too.

**Comment by SimonSimCity** [comment]
Is there anything left that's needed? How quickly could we publish this? I need it to analyze #17 - if I don't want to import the code manually.

**Comment by SimonSimCity** [comment]
I've now also updated the documentation, added the debug info you asked for and quite often renamed the other debug messages the way I thought it could be better understood intuitively. Is it OK as is?

**Pull request merged**
